"""
Index values in a series are generated by default. 
We can also define custom indexes at the time of creating series.

Below is a series of marks (grades) and the associated subjects can be defined as custom row indexes.
"""

import pandas as pd

# Create the s2 series with custom indexes
s2 = pd.Series([80, 93, 78, 85, 97], index=['English', 'Science', 'Social', 'Tamil', 'Maths'])

# Assign the series name
s2.name = "Student Marks"

# Assign the index name
s2.index.name = "Subject"

print(s2)
